/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;

public class App3 {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App3().getGreeting());
    }
}
